apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/dex
      value: |
        image: quay.io/redhat-cop/dex
        version: v2.22.0-openshift
        openShiftOAuth: true
  target:
    kind: ArgoCD