apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/sso/dex
      value:
        openShiftOAuth: true
  target:
    kind: ArgoCD