apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/oidcConfig
      value: |
        name: OpenShift Single Sign-On
        issuer: https://sso-sso.apps.home.ocplab.com/auth/realms/openshift
        clientID: openshift-gitops
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
  target:
    kind: ArgoCD